<?php
// $Id: translatablecomments.module,v 1.1 2008/04/15 21:23:05 davetrainer Exp $

/**
 * @file
 *
 * Makes comments translatable via the Google AJAX Language API.
 */
 
/**
 * Create the translation widget to display.
 */
function translatablecomments_nodeapi(&$node, $op, $teaser, $page) {
  switch ($op) {
    case 'view':
      drupal_set_html_head('<script type="text/javascript" src="http://www.google.com/jsapi"></script>');
      drupal_add_js('google.load("language", "1");', 'inline');
      drupal_add_js(drupal_get_path('module', 'translatablecomments') .'/jquery.translatablecomments.js');
      break;
  }
}
