<?php
// $Id$

/**
 * @file
 * file_description
 */

/**
 * Implementation of hook_menu().
 */
function mozes_menu() {
  $items = array();
  $items['admin/settings/mozes'] = array(
    'title' => 'Mozes',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mozes_admin_settings'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

/**
 * Admin settings form
 */
function mozes_admin_settings() {
  $form['mozes_redirect_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Mozes Redirect URL'),
    '#description' => t('A full URL to redirect to if a mobile browser is detected. If empty, no detection will happen.'),
    '#default_value' => variable_get('mozes_redirect_url', ''),
  );

  return system_settings_form($form);
}

/**
 * Implementation of hook_init().
 */
function mozes_init() {
  if (($url = variable_get('mozes_redirect_url', '')) && _mozes_is_mobile()) {
    drupal_goto($url);
  }
}

/**
 * Determine if the user agent is a mobile browser.
 */
function _mozes_is_mobile() {
  if (isset($_SESSION['mozes_is_mobile'])) {
    return $_SESSION['mozes_is_mobile'];
  }

  $is_mobile = FALSE;
  $ua = strtolower($_SERVER['HTTP_USER_AGENT']);

  $is_mobile = strpos($ua, 'sony') !== false
    || strpos($ua, 'symbian') !== false
    || strpos($ua, 'nokia') !== false
    || strpos($ua, 'samsung') !== false
    || strpos($ua, 'mobile') !== false
    || strpos($ua, 'windows ce') !== false
    || strpos($ua, 'epoc') !== false
    || strpos($ua, 'opera mini') !== false
    || strpos($ua, 'nitro') !== false
    || strpos($ua, 'j2me') !== false
    || strpos($ua, 'midp-') !== false
    || strpos($ua, 'cldc-') !== false
    || strpos($ua, 'netfront') !== false
    || strpos($ua, 'mot') !== false
    || strpos($ua, 'up.browser') !== false
    || strpos($ua, 'up.link') !== false
    || strpos($ua, 'audiovox') !== false
    || strpos($ua, 'blackberry') !== false
    || strpos($ua, 'ericsson,') !== false
    || strpos($ua, 'panasonic') !== false
    || strpos($ua, 'philips') !== false
    || strpos($ua, 'sanyo') !== false
    || strpos($ua, 'sharp') !== false
    || strpos($ua, 'sie-') !== false
    || strpos($ua, 'portalmmm') !== false
    || strpos($ua, 'blazer') !== false
    || strpos($ua, 'avantgo') !== false
    || strpos($ua, 'danger') !== false
    || strpos($ua, 'palm') !== false
    || strpos($ua, 'series60') !== false
    || strpos($ua, 'palmsource') !== false
    || strpos($ua, 'pocketpc') !== false
    || strpos($ua, 'smartphone') !== false
    || strpos($ua, 'rover') !== false
    || strpos($ua, 'ipaq') !== false
    || strpos($ua, 'au-mic,') !== false
    || strpos($ua, 'alcatel') !== false
    || strpos($ua, 'ericy') !== false
    || strpos($ua, 'up.link') !== false
    || strpos($ua, 'vodafone/') !== false
    || strpos($ua, 'wap1.') !== false
    || strpos($ua, 'wap2.') !== false;

    $_SESSION['mozes_is_mobile'] = $is_mobile;
    return $is_mobile;
}