<?php
// $Id: basque_services.module,v 1.1.2.2 2010/09/17 12:06:18 thecrow Exp $

/**
 * @file
 * Basque services that extend Sony Share module
 * Collected by Aiaraldea
 */

/**
 * Implementation of hook_sony_share().
 */
function basque_services_sony_share() {
  $links = array();

  $links['_eu_zabaldu'] = array(
    'name' => 'Zabaldu',
    'description' => t('Add a new on Zabaldu'),
    'link' => 'http://zabaldu.com/api/zabaldu_edo_bozkatu.php?url=<encoded-url>&title=<encoded-title>',
  );
  $links['_eu_bildu'] = array(
    'name' => 'Bildu',
    'description' => t('Bookmark this post on Bildu'),
    'link' => 'http://www.bildu.net/bookmarks/bildu?action=add&address=<encoded-url>&title=<encoded-title>',
  );
  $links['_eu_aupatu'] = array(
    'name' => 'Aupatu',
    'description' => t('Add a new on Aupatu'),
    'link' => 'http://www.aupatu.com/eu/submit.php?url=<encoded-url>&title=<encoded-title>',
  );

  return $links;
}
