<?php
// $Id$

/**
 * @file
 * Provide the bookmarking support for various browser
 */
function favorite_services_sony_share() {
  $links['favorite'] = array(
    'name' => 'Favorite',
    'description' => t('Add this page in your favorites'),
    'link' => url('', array('absolute' => TRUE, 'query' => '<encoded-url>#<encoded-title>')),
    'attributes' => array('style' => 'display:none;'),
    'javascript' => 'favorite_services.js',
  );
  return $links;
}
