<?php
// $Id$

/**
 * @file
 * Swedish services that extend Sony Share module
 * Bork, bork, bork'd by @persand
 */

/**
 * Implementation of hook_sony_share()
 */
function swedish_services_sony_share() {
  $links = array();

  $links['_se_bloggy'] = array(
    'name' => 'Bloggy',
    'description' => t('Share this on Bloggy'),
    'link' => 'http://bloggy.se/home/?status=<encoded-url>+--+<encoded-title>',
  );
  $links['_se_pusha'] = array(
    'name' => 'Pusha',
    'description' => t('Share this on Pusha'),
    'link' => 'http://pusha.se/posta?url=<encoded-url>&title=<encoded-title>',
  );

  return $links;
}
