<?php
$content[type]  = array (
  'name' => 'Why I\'m A Fan',
  'type' => 'fan',
  'description' => 'A testimonial about why this person is a fan.',
  'title_label' => 'Title',
  'body_label' => 'Body',
  'min_word_count' => '0',
  'help' => '',
  'node_options' => 
  array (
    'status' => true,
    'promote' => false,
    'sticky' => false,
    'revision' => false,
    'moderate' => false,
  ),
  'language_content_type' => '0',
  'comment' => '2',
  'comment_type' => '',
  'comment_view' => '',
  'usernodes_limit' => '1',
  'old_type' => 'fan',
  'orig_type' => '',
  'module' => 'node',
  'custom' => '1',
  'modified' => '1',
  'locked' => '0',
);
