<?php
// $Id$

/**
 * @file
 * Glue code module for the Sony Multisite platform admin interfaces.
 */

/**
 * Implementation of hook_menu().
 */
function sony_admin_menu() {
  $items = array();

  $items['admin/deployment'] = array(
    'title' => 'Deployment',
    'description' => 'Deployment related administration tasks',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer deployment settings'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/deployment/live'] = array(
    'title' => 'Live Settings',
    'description' => 'Put the site into Live Production mode.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sony_admin_deployment_settings_form', 'live'),
    'access arguments' => array('administer deployment settings'),
    'file' => 'sony_admin.deployment.inc',
  );

  $items['admin/deployment/dev'] = array(
    'title' => 'Dev Settings',
    'description' => 'Put the site into Development mode.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sony_admin_deployment_settings_form', 'dev'),
    'access arguments' => array('administer deployment settings'),
    'file' => 'sony_admin.deployment.inc',
  );

  return $items;
}

function sony_admin_form_block_admin_configure_alter(&$form, $form_state) {
  $module = $form['module']['#value'];
  $delta = $form['delta']['#value'];
  $info = module_invoke($module, 'block', 'list');
  $default_cache = isset($info[$delta]['cache']) ? $info[$delta]['cache'] : BLOCK_CACHE_PER_ROLE;
  $block = db_fetch_array(db_query("SELECT * FROM {blocks} WHERE module = '%s' AND delta = '%s'", $module, $delta));

  $form['block_cache'] = array(
    '#type' => 'fieldset',
    '#title' => t('Block cache settings'),
    '#collapsed' => TRUE,
    '#collapsible' => TRUE,
    '#tree' => 1,
    '#weight' => 0,
  );

  $options = array(
      BLOCK_NO_CACHE       => 'No cache',
      BLOCK_CACHE_PER_ROLE => 'Cached per role',
      BLOCK_CACHE_PER_USER => 'Cached per user',
      BLOCK_CACHE_PER_PAGE => 'Cached per page',
      BLOCK_CACHE_GLOBAL   => 'Cached globally',
  );
  $options[$default_cache] .= ' ('. t('Default setting for this type of block') .')';

  $form['block_cache']['cache'] = array(
    '#type' => 'radios',
    '#title' => t('Cache'),
    '#options' => $options,
    '#default_value' => $block['cache'],
  );
  $form['#submit'][] = 'sony_admin_block_admin_configure_submit';
}

function sony_admin_block_admin_configure_submit($form, &$form_state) {
  db_query("UPDATE {blocks} SET cache = %d WHERE module = '%s' AND delta = '%s'", $form_state['values']['block_cache']['cache'], $form_state['values']['module'], $form_state['values']['delta']);
}

/**
 * Implementation of hook_views_api().
 */
function sony_admin_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'sony_admin'),
  );
}
