<?php

include_once('m2_product.features.inc');

/**
 * Implementation of hook_menu().
 */
function m2_product_menu() {
  $items['admin/content/m2api/id_matcher/products'] = array(
    'title' => 'Products',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('m2_product_products_match_form'),
    'access arguments' => array('administer m2'),
    'file' => 'm2_product.pages.inc',
    'weight' =>'0',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function m2_product_ctools_plugin_directory($module, $plugin) {
  if ($module == 'm2api') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implementation of hook_theme().
 */
function m2_product_theme() {
  return array(
    'm2_product_products_match_form' => array(
      'arguments' => array('form' => NULL),
      'file' => 'm2_product.pages.inc',
    ),
  );
}

/**
 * Implementation of hook_m2api_node_types_alter().
 */
function m2_product_m2api_node_types_alter(&$types) {
  $types['m2_product'] = array('generic_physical_product', 'product_group');
}