<?php
// $Id$

/**
 * Implementation of hook_form_alter().
 */
function submitagain_form_alter(&$form, &$form_state, $form_id) {

  // alter node create forms
  if (strpos($form_id, '_node_form') && !isset($form['nid']['#value'])) {
    $type = $form['type']['#value'];
    if (variable_get('submitagain_' . $type, false)) {

      $form['buttons']['submit_again'] = array (
        '#type' => 'submit',
        '#value' => t('Submit and create another'),
        '#weight' => 55,
      );
      
      $form['#submit']['submitagain_redirect'] = array($type);
    }
  }
  
  // alter content type settings
  if ($form_id == 'node_type_form' && isset($form['identity']['type'])) {
    $form['submission']['submitagain'] = array (
      '#type' => 'checkbox',
      '#title' => t('Submit Again?'),
      '#default_value' => variable_get('submitagain_' . $form['#node_type']->type, false),
      '#description' => t('Enable this checkbox if you want to provide a "Submit and create another" button for your users.'),
      
    );
  }
}

function submitagain_redirect($id, $form, $type) {
  if ($_POST['op'] == t('Submit and create another')) {
    return 'node/add/' . $type;
  }
}

function submitagain_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($op == 'insert' && $_POST['op'] == t('Submit and create another')) {
    theme('submitagain_message', $node);
  }
}

function theme_submitagain_message(&$node) {
  $link = l(url('node/' . $node->nid), 'node/' . $node->nid);
  drupal_set_message(t('You may visit your post at !link', array('!link' => $link)));
}
