<?php

/**
 * Implementation of hook_perm().
 */
function bro_perm() {
  return array('participate in bro chat');
}

/**
 * Implementation of hook_init().
 */
function bro_init() {
  $type = variable_get('bro_type', 'disabled');
  if ($type == 'jabber' && (empty($_COOKIE['bro_user']) || empty($_COOKIE['bro_nick']) || empty($_COOKIE['bro_hash']))) {
    bro_set_cookies();
  }
  elseif ($type == 'facebook') {
    setcookie('bro_logged_in', (user_is_logged_in() ? '1' : '0'), 0, '/');
  }
}

/**
 * Set the cookies to communicate with the BRO.
 */
function bro_set_cookies() {
  global $user;
  
  $domain = variable_get('bro_chat_domain', 'j.sonymusicdigital.com');
  $secret = variable_get('bro_chat_secret', '');

  if (user_access('participate in bro chat')) {
    $name = $user->uid;
    $nick = check_plain($user->name);
  }
  else {
    $name = session_id();
    $nick = 'anonymous-'. session_id();
  }

  $jid = $name .'@'. $domain .'/drupal';
  $timestamp = time();
  $hash = md5($name . $timestamp . $secret);
	
  setcookie('bro_jid', $jid, 0, '/');
  setcookie('bro_nick', $nick, 0, '/');
  setcookie('bro_hash', $hash . $timestamp, 0, '/');
}

/**
 * Implementation of hook_user().
 */
function bro_user($op, &$edit, &$account, $category = NULL) {
  $type = variable_get('bro_type', 'disabled');
  if ($type == 'jabber' && ($op == 'login' || $op == 'logout')) {
    bro_set_cookies();
  }
  elseif ($type == 'facebook' && ($op == 'login' || $op == 'logout')) {
    setcookie('bro_logged_in', (($op == 'login') ? '1' : '0'), 0, '/');
  }
}

/**
 * Implementation of hook_footer().
 */
function bro_footer() {
  switch (variable_get('bro_type', 'disabled')) {
    case 'jabber':
      return bro_render_jabber_chat();
    case 'facebook':
      return bro_render_facebook_chat();
  }
}

function bro_render_jabber_chat() {
  $domain = variable_get('bro_chat_domain', 'j.sonymusicdigital.com');
  $config = variable_get('bro_chat_config', '');

  if ($domain && $config) {
    $output = '<script type="text/javascript" src="http://'. $domain .':5280/client/bro.min.js"></script>';
    $output .= '<script type="text/javascript">';
    //$output .= 'BRO.debug = true; ';
    $output .= 'BRO.init("'. $config .'");</script>';
    return $output;
  }
}

function bro_render_facebook_chat() {
  $path = base_path() . drupal_get_path('module', 'bro') .'/facebook';

  // include jquery_ui if needed
  $output .= '<script type="text/javascript" src="'. $path .'/javascripts/jquery-ui.js"></script>';

  $output .= '<script type="text/javascript" src="'. $path .'/bro.min.js"></script>';
  
  $config = variable_get('bro_chat_config', '');

  $output .= '<script type="text/javascript">';
  //$output .= 'BRO.debug = true; ';
  $output .= '$(window).load(function() { BRO.init("'. $config .'"); });</script>';
  
  return $output;
}

/**
 * Implementation of hook_menu().
 */
function bro_menu() {
  return array(
    'admin/settings/bro' => array(
      'title' => 'BRO',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('bro_admin_settings'),
      'access arguments' => array('administer site configuration'),
    ),
  );
}

/**
 * Admin form for the BRO.
 */
function bro_admin_settings() {
  $form['bro_type'] = array(
    '#type' => 'radios',
    '#title' => t('BRO Type'),
    '#options' => array(
      'jabber' => t('Jabber chat'),
      'facebook' => t('Facebook'),
      'disabled' => t('Disabled'),
    ),
    '#default_value' => variable_get('bro_type', 'disabled'),
  );

  $form['bro_chat_config'] = array(
    '#type' => 'textfield',
    '#title' => t('Chat config'),
    '#default_value' => variable_get('bro_chat_config', ''),
  );

  $form['bro_chat_domain'] = array(
    '#type' => 'textfield',
    '#title' => t('Chat domain'),
    '#default_value' => variable_get('bro_chat_domain', 'j.sonymusicdigital.com'),
  );

  $form['bro_chat_secret'] = array(
    '#type' => 'textfield',
    '#title' => t('Secret key'),
    '#default_value' => variable_get('bro_chat_secret', ''),
  );

  return system_settings_form($form);
}
