<?php
// $Id$

/**
 * @file
 * jQuery form validation add-on for the Drupal Forms API.
 */

/**
 * Implementation of hook_menu().
 */
function jquery_validation_menu() {
  $items = array();
  $items['jquery_validation'] = array(
    'title' => 'jQuery Validation Test',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('jquery_validation_test_form'),
    'access arguments' => array('access devel information'),
    'file' => 'jquery_validation.pages.inc',
  );

  $items['jquery_validation/username'] = array(
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
    'page callback' => 'jquery_validation_register_username',
  );
  $items['jquery_validation/email'] = array(
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
    'page callback' => 'jquery_validation_register_email',
  );
  return $items;
}

/**
 * Implementation of hook_form_alter().
 */
function jquery_validation_form_alter(&$form, $form_state) {
  if ($form['#jquery_validation']) {
    $form['#after_build'][] = 'jquery_validation_attach';
  }
}

/**
 * #after_build callback.
 * Attach the jquery validation rules to the form and load necessary scripts.
 */
function jquery_validation_attach($form, &$form_state) {
  $data = _jquery_validation_attach($form);
  drupal_add_js(array('jquery_validation' => array($form['#id'] => $data)), 'setting');

  $path = drupal_get_path('module', 'jquery_validation');
  drupal_add_js($path .'/lib/jquery-validate/jquery.validate.js');
  drupal_add_js($path .'/lib/jquery.ajaxqueue.js');
  drupal_add_js($path .'/jquery_validation.js');

  return $form;
}

/**
 * Recursive function for traversing FAPI array, looking for jquery validation
 * rules.
 */
function _jquery_validation_attach($form) {
  $data = array();

  foreach (element_children($form) as $key) {
    $data += _jquery_validation_attach($form[$key]);
  }

  if (is_array($form['#jquery_validation']) && !empty($form['#jquery_validation'])) {
    $data[$form['#name']] = $form['#jquery_validation'];
  }

  return $data;
}

function jquery_validation_register_username() {
  $error = user_validate_name($_GET['name']);
  if (!$error) {
    if (db_result(db_query("SELECT COUNT(*) FROM {users} WHERE LOWER(name) = LOWER('%s')", $_GET['name'])) > 0) {
      $error = t('The name %name is already taken.', array('%name' => $_GET['name']));
    }
    elseif (drupal_is_denied('user', $_GET['name'])) {
      $error = t('The name %name has been denied access.', array('%name' => $_GET['name']));
    }
  };

  $result = array(
    'valid' => !$error,
    'message' => $error,
  );
  print drupal_to_js($result);
  exit();
}

function jquery_validation_register_email() {
  $error = user_validate_mail($_GET['mail']);
  if (!$error) {
    if (db_result(db_query("SELECT COUNT(*) FROM {users} WHERE LOWER(mail) = LOWER('%s')", $_GET['mail'])) > 0) {
      $error = t('The e-mail address %email is already registered. <a href="@password">Have you forgotten your password?</a>', array('%email' => $_GET['mail'], '@password' => url('user/password')));
    }
    elseif (drupal_is_denied('mail', $_GET['mail'])) {
      $error = t('The e-mail address %email has been denied access.', array('%email' => $_GET['mail']));
    }
  };

  $result = array(
    'valid' => !$error,
    'message' => $error,
  );
  print drupal_to_js($result);
  exit();
}
