<?php
// $Id: friendlist_import_bl2.module,v 1.1.2.9 2008/10/11 18:47:29 mercmobily Exp $


/**
 * @file
 * Friendlist's Buddylist2 importer.
 */


/**
 * Implementation of hook_menu().
 */
function friendlist_import_bl2_menu() {

  $items['admin/settings/friendlist_import_bl2'] = array(
    'title' => 'Friendlist Buddylist2 importer',
    'description' => 'Import data from Buddylist2',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('friendlist_import_bl2_form'),
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Implementation of hook_form().
 *
 * This is the importer's form.
 */
function friendlist_import_bl2_form(&$form_state, $edit = NULL) {

  drupal_set_title(t("Buddylist2 data importer"));

  $form['info'] = array(
    '#value' => t('<h1>This is DESTRUCTIVE. YOU WILL LOSE ALL YOUR Friendlist DATA. WATCH OUT.</h1>')
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Import'),
  );

  return $form;

}

/**
 * This function actually does all of the importing.
 */
function friendlist_import_bl2_form_submit($form, &$form_state) {

  // Delete the existing relations and relation types.
  db_query("DELETE FROM {friendlist_relation_types}");
  db_query("DELETE FROM {friendlist_relations}");
  db_query("DELETE FROM {friendlist_statuses}");

  // Get the relation types from Buddylist.
  $r = db_query("SELECT * FROM {buddylist_relationtypes}");
  while ($row = db_fetch_object($r)) {
    db_query("INSERT INTO {friendlist_relation_types} SET rtid = %d, name = '%s', name_p = '%s', oneway = '%s', active = %d", $row->rtid, $row->name, $row->name, $row->oneway, $row->active);
    if ($row->oneway) {
      $oneway_list[$row->rtid] = TRUE;
    }
  }


  $r = db_query("SELECT * FROM {buddylist_relations}");
  while ($row = db_fetch_object($r)) {

    // Case #1: it's a 1-way relationship, "just add it" (if it's approved).
    if ($oneway_list[$row->rtid]) {

        if ($row->state) {

          friendlist_api_relation_add($row->requester_id, $row->requestee_id, $row->rtid, '', FALSE);

          friendlist_api_set_relations_field($row->requester_id, $row->requestee_id, $row->rtid, 'create_time', $row->create_time);
          friendlist_api_set_status_field($row->requester_id, $row->requestee_id, $row->rtid, 'last_update_time', $row->create_time);
          friendlist_api_set_status_field($row->requestee_id, $row->requester_id, $row->rtid, 'last_update_time', $row->create_time);
        }

    // Case #2: it's a 2-way relationship. Watch out: only add the "other side"
    // if it's been approved.
    }
    else {

      friendlist_api_relation_add($row->requester_id, $row->requestee_id, $row->rtid, '', FALSE);

      friendlist_api_set_relations_field($row->requester_id, $row->requestee_id, $row->rtid, 'create_time', $row->create_time);
      friendlist_api_set_status_field($row->requester_id, $row->requestee_id, $row->rtid, 'last_update_time', $row->create_time);
      friendlist_api_set_status_field($row->requestee_id, $row->requester_id, $row->rtid, 'last_update_time', $row->create_time);


      db_query("UPDATE {friendlist_relations} SET create_time = %d, message = '%s' WHERE requester_id = '%d' AND requestee_id = %d AND rtid = %d", $row->create_time, $row->message, $row->requester_id, $row->requestee_id, $row->rtid);

      if ($row->state) {

        friendlist_api_relation_add($row->requestee_id, $row->requester_id, $row->rtid, '', FALSE);

        friendlist_api_set_relations_field($row->requestee_id, $row->requester_id, $row->rtid, 'create_time', $row->create_time);
        friendlist_api_set_status_field($row->requestee_id, $row->requester_id, $row->rtid, 'last_update_time', $row->create_time);
        friendlist_api_set_status_field($row->requester_id, $row->requestee_id, $row->rtid, 'last_update_time', $row->create_time);

      }
    }
  }

  drupal_set_message(t("Done!"));
  drupal_goto('admin/settings/friendlist_import_bl2');
}

